version: "3.4"

services:
  frontend:
    image: react:latest
    container_name: react
    build: frontend
    ports:
      - 3000:80

  backend:
    image: api:latest
    build: Api
    container_name: api
    ports:
      - 5013:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  identity:
    image: identityserver:latest
    build: IdentityServer
    container_name: identityserver
    ports:
      - 5001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  

networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.4
